name: weather_app
description: A weather forecast app for Hanoi using OpenWeatherMap and SQLite.
version: 1.0.0

environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  sqflite: ^2.3.3
  sqflite_common_ffi: ^2.3.3
  path: ^1.9.0
  intl: ^0.20.2 # Cập nhật lên phiên bản mới nhất

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Cập nhật lên phiên bản mới nhất

flutter:
  uses-material-design: true